apiVersion: 1
policies:
  - orgId: 1
    receiver: email-notifications
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 5m
    routes:
      - receiver: ai-incident-summary
        group_by:
          - grafana_folder
          - alertname
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 5m
        continue: true
      - receiver: email-notifications
        group_by:
          - grafana_folder
          - alertname
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 5m
