auth_enabled: false

target: all

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

frontend_worker:
  frontend_address: 127.0.0.1:9096

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: azure
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  azure:
    account_name: blobstoragelgtmfpv1
    account_key: ${AZURE_STORAGE_ACCOUNT_KEY}
    container_name: loki
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h

limits_config:
  retention_period: 72h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_query_lookback: 72h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 5m
  retention_enabled: true
  retention_delete_delay: 2m
  delete_request_store: azure

analytics:
  reporting_enabled: false
