target: all

server:
  http_listen_port: 4040
  grpc_listen_port: 4041

multitenancy_enabled: false

storage:
  backend: azure
  azure:
    account_name: blobstoragelgtmfpv1
    account_key: ${AZURE_STORAGE_ACCOUNT_KEY}
    container_name: pyroscope-data
    endpoint_suffix: blob.core.windows.net

memberlist:
  join_members: []

pyroscopedb:
  data_path: /data

analytics:
  reporting_enabled: false
